### ISSUE TITLE
Rebuild OncoSNP-Seq for Ubuntu 20.04

### ISSUE THREAD

**Issue by rpep** [bear-rsg/easybuild-easyconfigs#751]
https://bear-apps.bham.ac.uk/applications/2020a/OncoSNP-Seq/2.01/ currently only on EL8

**Comment by orbsmiv** [comment]
@edmondac it looks like this was done under https://github.com/bear-rsg/easybuild-easyconfigs/pull/443. Any ideas as to why it's no longer available under Ubuntu 20.04? (Happy to rebuild.)

**Comment by edmondac** [comment]
Must have been a mistake, I guess. It's certainly not there now!

Please go ahead and build it @orbsmiv

**Comment by orbsmiv** [comment]
Ah, this rings a bell:
```
== Running pre-configure hook...
  >> running command:
	[started at: 2021-11-16 09:35:24]
	[working dir: /dev/shm/carpenjj-admin-2020a-Ubuntu20.04/MCR/R2013b/system-system]
	[output logged in /scratch/carpenjj-admin-Ubuntu20.04/eb-8zymlp1u/easybuild-run_cmd-ust_0z04.log]
	LANG=C sed -i "s/[\d128-\d255]//g" /dev/shm/carpenjj-admin-2020a-Ubuntu20.04/MCR/R2013b/system-system/my_installer_input.txt
  >> command completed: exit 0, ran in < 1s
ERROR: Traceback (most recent call last):
  File "/rds/bear-sysadmin/configmgmt/easybuild/2020a/src/easybuild-framework/easybuild/main.py", line 115, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/rds/bear-sysadmin/configmgmt/easybuild/2020a/src/easybuild-framework/easybuild/framework/easyblock.py", line 3244, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/rds/bear-sysadmin/configmgmt/easybuild/2020a/src/easybuild-framework/easybuild/framework/easyblock.py", line 3149, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/rds/bear-sysadmin/configmgmt/easybuild/2020a/src/easybuild-framework/easybuild/framework/easyblock.py", line 3004, in run_step
    step_method(self)()
  File "/rds/bear-sysadmin/configmgmt/easybuild/2020a/src/easybuild-easyblocks/easybuild/easyblocks/m/mcr.py", line 78, in configure_step
    config = read_file(configfile)
  File "/rds/bear-sysadmin/configmgmt/easybuild/2020a/src/easybuild-framework/easybuild/tools/filetools.py", line 195, in read_file
    txt = handle.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 6034: invalid start byte
```
@rpep I have a vague recollection that we were unable to install this old version of MCR (R2013b) under Ubuntu, which is why it was dropped. (The researcher at the time didn't require it.)

**Comment by rpep** [comment]
OK, will pass the ticket over to you to have that discussion

Edit: it's still in to be assigned anyway so will leave it there

**Comment by orbsmiv** [comment]
Resolved by https://github.com/bear-rsg/easybuild-easyblocks/pull/97
Ubuntu 20 version built on live
